title: Chandrani Kumari
logo: assets/img/img1.jpg
description: Post-doctoral researcher in Computational Biology at Wisconsin Institute for Discovery, University of Wisconsin
#show_downloads: true
#theme: jekyll-theme-minimal
theme: Architect
